import { StyleSheet } from "react-native";
import { AuthColors } from "./AuthColors";

const ReportStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  header: {
    backgroundColor: "#039568",
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    flex: 1,
    textAlign: "left",
  },
  filterButton: {
    backgroundColor: "#FFF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 25,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    minWidth: 80,
    justifyContent: "center",
    alignItems: "center",
  },

  filterText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#039568",
  },
  reportCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    marginVertical: 5,
    marginHorizontal: 10,
    backgroundColor: "#FFF",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  reportIndex: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#039568",
    marginRight: 10,
  },
  reportContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  reportDescription: {
    fontSize: 16,
    color: "#333",
    marginBottom: 5,
  },
  reportDate: {
    fontSize: 14,
    color: "#888",
    marginBottom: 5,
  },
  reportStatus: {
    fontSize: 14,
    fontWeight: "bold",
  },
  statusComplete: {
    color: "#4CAF50",
  },
  statusPending: {
    color: "#FF9800",
  },
  scheduleButton: {
    backgroundColor: "#FF9800",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  scheduleButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },

  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "90%",
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#039568",
  },
  modalItem: {
    marginBottom: 15,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#555",
  },
  modalValue: {
    fontSize: 16,
    color: "#333",
  },
  closeButton: {
    marginTop: 20,
    alignSelf: "center",
    backgroundColor: "#039568",
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 20,
  },
  closeButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  input: {
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 5,
    padding: 10,
    fontSize: 16,
    marginBottom: 10,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  editButton: {
    backgroundColor: "#FFA726",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  editButton: {
    backgroundColor: "#FFA726",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  editButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },

  saveButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  deleteButton: {
    backgroundColor: "#E53935",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  deleteButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  closeButton: {
    marginTop: 20,
    alignSelf: "center",
    backgroundColor: "#4F7670",
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 20,
  },
  closeButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  dateFilterContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  dateLabel: {
    fontSize: 16,
    marginRight: 10,
  },
  dateInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginRight: 10,
    height: 50,
    fontSize: 16,
  },
  applyButton: {
    backgroundColor: "#7D40E7",
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  applyFilterText: {
    color: "#fff",
    fontWeight: "bold",
  },
  dateStatusContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginVertical: 10,
    textAlign: "left",
  },
  checklistButton: {
    backgroundColor: "#9CB4D4",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  statusButton: {
    backgroundColor: "#92BEA9",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
});

export default ReportStyles;
